name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux-x64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libusb-1.0-0-dev libhidapi-dev pkg-config
    - name: make
      run: make

  build-linux-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libusb-1.0-0-dev libhidapi-dev pkg-config
    - name: make
      run: make

  build-windows-x64:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        install: >-
          base-devel
          mingw-w64-ucrt-x86_64-toolchain
          mingw-w64-ucrt-x86_64-libusb
          mingw-w64-ucrt-x86_64-hidapi
          mingw-w64-ucrt-x86_64-pkgconf

    - name: Build
      shell: msys2 {0}
      run: make steam-haptics-singer.exe
